-- Conecta Trindade - promoção manual de um usuário para administrador.
-- Segurança: não inclua e-mails, senhas, tokens ou outros dados pessoais neste arquivo.
--
-- No SQL Editor do projeto Supabase, primeiro localize o UUID do usuário em
-- Authentication > Users. Em seguida, execute a instrução abaixo substituindo
-- SOMENTE o UUID pelo valor real da conta administrativa criada no Supabase.
--
-- UPDATE public.profiles
-- SET role = 'admin', updated_at = timezone('utc'::text, now())
-- WHERE id = '<UUID_DO_USUARIO_AUTH>';
--
-- Depois valide:
-- SELECT id, email, nome, role FROM public.profiles
-- WHERE id = '<UUID_DO_USUARIO_AUTH>';
