export type TipoOrgaoPublico =
  | 'PREFEITURA'
  | 'SECRETARIA'
  | 'UBS'
  | 'HOSPITAL_UPA'
  | 'ESCOLA'
  | 'CMEI'
  | 'PARQUE'
  | 'SERVICO';

export interface OrgaoPublico {
  id: string;
  nome: string;
  tipo: TipoOrgaoPublico;
  tipoLabel: string;
  emoji: string;
  cor: string;
  bgBadge: string;
  latitude: number;
  longitude: number;
  endereco: string;
  bairro: string;
  telefone?: string;
  horario?: string;
  descricao?: string;
}

export const ORGAOS_PUBLICOS_TRINDADE: OrgaoPublico[] = [
  // --- PREFEITURA & GESTÃO MUNICIPAL ---
  {
    id: 'pref-sede',
    nome: 'Prefeitura Municipal de Trindade (Palácio das Rosas)',
    tipo: 'PREFEITURA',
    tipoLabel: 'Sede Administrativa',
    emoji: '🏛️',
    cor: '#006653',
    bgBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    latitude: -16.655928,
    longitude: -49.488855,
    endereco: 'Rua Moisés Batista, Praça da Prefeitura',
    bairro: 'Vila Pai Eterno',
    telefone: '(62) 3506-7000',
    horario: 'Seg a Sex: 08:00 às 17:00',
    descricao: 'Sede do Poder Executivo Municipal e gabinete do Prefeito.',
  },
  {
    id: 'pref-trindade-2',
    nome: 'Subprefeitura da Região Leste (Trindade II)',
    tipo: 'PREFEITURA',
    tipoLabel: 'Subprefeitura',
    emoji: '🏛️',
    cor: '#006653',
    bgBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    latitude: -16.633469,
    longitude: -49.397727,
    endereco: 'Rua das Araras, quadra 23',
    bairro: 'Jardim Floresta / Trindade II',
    telefone: '(62) 3506-7050',
    horario: 'Seg a Sex: 08:00 às 17:00',
    descricao: 'Atendimento descentralizado da administração municipal para a Região Leste.',
  },
  {
    id: 'camara-municipal',
    nome: 'Câmara Municipal de Trindade',
    tipo: 'PREFEITURA',
    tipoLabel: 'Poder Legislativo',
    emoji: '⚖️',
    cor: '#0f766e',
    bgBadge: 'bg-teal-100 text-teal-800 border-teal-300',
    latitude: -16.653400,
    longitude: -49.489900,
    endereco: 'Praça Constantino Xavier, Centro',
    bairro: 'Centro',
    telefone: '(62) 3505-1234',
    horario: 'Seg a Sex: 08:00 às 18:00',
    descricao: 'Palácio Vereador José Ferreira - Sede do Legislativo Municipal.',
  },
  {
    id: 'sec-obras',
    nome: 'Secretaria Municipal de Obras e Serviços Públicos',
    tipo: 'SECRETARIA',
    tipoLabel: 'Secretaria Municipal',
    emoji: '🚜',
    cor: '#d97706',
    bgBadge: 'bg-amber-100 text-amber-800 border-amber-300',
    latitude: -16.652100,
    longitude: -49.493200,
    endereco: 'Av. Manoel Monteiro, esq. com Rua 10',
    bairro: 'Setor Central',
    telefone: '(62) 3506-7020',
    horario: 'Seg a Sex: 07:00 às 17:00',
    descricao: 'Responsável por pavimentação, tapa-buracos, iluminação pública e infraestrutura.',
  },
  {
    id: 'sec-saude',
    nome: 'Secretaria Municipal de Saúde',
    tipo: 'SECRETARIA',
    tipoLabel: 'Secretaria Municipal',
    emoji: '🩺',
    cor: '#dc2626',
    bgBadge: 'bg-red-100 text-red-800 border-red-300',
    latitude: -16.660148,
    longitude: -49.496410,
    endereco: 'Rua Padre Orlando de Moraes, nº 230',
    bairro: 'Vila Pai Eterno',
    telefone: '(62) 3506-7080',
    horario: 'Seg a Sex: 07:30 às 17:00',
    descricao: 'Gestão da rede municipal de saúde, unidades básicas e vigilância sanitária.',
  },
  {
    id: 'sec-educacao',
    nome: 'Secretaria Municipal de Educação',
    tipo: 'SECRETARIA',
    tipoLabel: 'Secretaria Municipal',
    emoji: '📚',
    cor: '#2563eb',
    bgBadge: 'bg-blue-100 text-blue-800 border-blue-300',
    latitude: -16.654200,
    longitude: -49.490800,
    endereco: 'Rua Rocha Lima, nº 115',
    bairro: 'Centro',
    telefone: '(62) 3506-7040',
    horario: 'Seg a Sex: 08:00 às 17:00',
    descricao: 'Coordenação pedagógica e gestão das escolas e creches municipais.',
  },
  {
    id: 'vapt-vupt',
    nome: 'Vapt Vupt / Central do Cidadão Trindade',
    tipo: 'SERVICO',
    tipoLabel: 'Atendimento ao Cidadão',
    emoji: '🏢',
    cor: '#0284c7',
    bgBadge: 'bg-sky-100 text-sky-800 border-sky-300',
    latitude: -16.651500,
    longitude: -49.492500,
    endereco: 'Galeria Trindade Shopping, Av. Manoel Monteiro',
    bairro: 'Centro',
    telefone: '(62) 3505-8900',
    horario: 'Seg a Sex: 08:00 às 17:00',
    descricao: 'Emissão de documentos, tributos municipais e atendimento presencial.',
  },

  // --- SAÚDE (UPA, HOSPITAL E UBS) ---
  {
    id: 'upa-tiradentes',
    nome: 'UPA 24h Dilson Alberto de Souza',
    tipo: 'HOSPITAL_UPA',
    tipoLabel: 'Unidade de Pronto Atendimento 24h',
    emoji: '🚨',
    cor: '#dc2626',
    bgBadge: 'bg-red-100 text-red-800 border-red-300',
    latitude: -16.636967,
    longitude: -49.412640,
    endereco: 'Avenida Tiradentes, s/n',
    bairro: 'Setor Cristina',
    telefone: '(62) 3506-7200',
    horario: 'Atendimento ininterrupto 24 horas',
    descricao: 'Urgência e emergência médica clínica e pediátrica.',
  },
  {
    id: 'hetrin-hospital',
    nome: 'Hospital Estadual de Trindade (Hetrin)',
    tipo: 'HOSPITAL_UPA',
    tipoLabel: 'Hospital de Referência',
    emoji: '🏥',
    cor: '#b91c1c',
    bgBadge: 'bg-rose-100 text-rose-800 border-rose-300',
    latitude: -16.648200,
    longitude: -49.485100,
    endereco: 'Rua 3, nº 200',
    bairro: 'Vila Redenção',
    telefone: '(62) 3121-5400',
    horario: 'Atendimento 24 horas',
    descricao: 'Atendimento hospitalar de média complexidade, cirurgias e maternidade.',
  },
  {
    id: 'ubs-santuario',
    nome: 'UBS Santuário Novo',
    tipo: 'UBS',
    tipoLabel: 'Unidade Básica de Saúde',
    emoji: '🏥',
    cor: '#e11d48',
    bgBadge: 'bg-red-50 text-red-700 border-red-200',
    latitude: -16.673424,
    longitude: -49.484132,
    endereco: 'Rua 135, quadra 42',
    bairro: 'Setor Santuário',
    telefone: '(62) 3506-7085',
    horario: 'Seg a Sex: 07:00 às 17:00',
    descricao: 'Consultas médicas, vacinação, pré-natal e curativos.',
  },
  {
    id: 'ubs-pai-eterno',
    nome: 'UBS Vila Pai Eterno',
    tipo: 'UBS',
    tipoLabel: 'Unidade Básica de Saúde',
    emoji: '🏥',
    cor: '#e11d48',
    bgBadge: 'bg-red-50 text-red-700 border-red-200',
    latitude: -16.657500,
    longitude: -49.487200,
    endereco: 'Av. Raimundo de Aquino, nº 840',
    bairro: 'Vila Pai Eterno',
    telefone: '(62) 3506-7087',
    horario: 'Seg a Sex: 07:00 às 17:00',
    descricao: 'Atendimento de saúde da família para a região do Santuário Matriz.',
  },
  {
    id: 'ubs-centro',
    nome: 'UBS Central (Dr. Waldir Graciano)',
    tipo: 'UBS',
    tipoLabel: 'Unidade Básica de Saúde',
    emoji: '🏥',
    cor: '#e11d48',
    bgBadge: 'bg-red-50 text-red-700 border-red-200',
    latitude: -16.654800,
    longitude: -49.491600,
    endereco: 'Rua do Comércio, nº 420',
    bairro: 'Centro',
    telefone: '(62) 3506-7090',
    horario: 'Seg a Sex: 07:00 às 17:00',
    descricao: 'Estratégia Saúde da Família, vacinas e distribuição de medicamentos.',
  },
  {
    id: 'ubs-maysa',
    nome: 'UBS Setor Maysa I',
    tipo: 'UBS',
    tipoLabel: 'Unidade Básica de Saúde',
    emoji: '🏥',
    cor: '#e11d48',
    bgBadge: 'bg-red-50 text-red-700 border-red-200',
    latitude: -16.639800,
    longitude: -49.392100,
    endereco: 'Rua São Luiz, quadra 18',
    bairro: 'Setor Maysa I',
    telefone: '(62) 3506-7093',
    horario: 'Seg a Sex: 07:00 às 17:00',
    descricao: 'Unidade de referência em atenção primária da Grande Região Leste.',
  },
  {
    id: 'ubs-pontakayana',
    nome: 'UBS Setor Pontakayana',
    tipo: 'UBS',
    tipoLabel: 'Unidade Básica de Saúde',
    emoji: '🏥',
    cor: '#e11d48',
    bgBadge: 'bg-red-50 text-red-700 border-red-200',
    latitude: -16.662500,
    longitude: -49.462800,
    endereco: 'Av. Pontakayana, quadra 10',
    bairro: 'Setor Pontakayana',
    telefone: '(62) 3506-7095',
    horario: 'Seg a Sex: 07:00 às 17:00',
    descricao: 'Acolhimento da comunidade, vacinas e visitas comunitárias.',
  },

  // --- CMEIS (EDUCAÇÃO INFANTIL / CRECHES) ---
  {
    id: 'cmei-leda-taveira',
    nome: 'CMEI Professora Leda Taveira',
    tipo: 'CMEI',
    tipoLabel: 'CMEI - Creche Municipal',
    emoji: '👶',
    cor: '#9333ea',
    bgBadge: 'bg-purple-100 text-purple-800 border-purple-300',
    latitude: -16.658200,
    longitude: -49.486100,
    endereco: 'Rua São Sebastião, nº 180',
    bairro: 'Vila Pai Eterno',
    telefone: '(62) 3506-7110',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Centro Municipal de Educação Infantil para bebês e crianças de 0 a 5 anos.',
  },
  {
    id: 'cmei-maria-pires',
    nome: 'CMEI Maria Pires Perillo',
    tipo: 'CMEI',
    tipoLabel: 'CMEI - Creche Municipal',
    emoji: '👶',
    cor: '#9333ea',
    bgBadge: 'bg-purple-100 text-purple-800 border-purple-300',
    latitude: -16.651800,
    longitude: -49.489100,
    endereco: 'Rua 15 de Novembro, nº 95',
    bairro: 'Centro',
    telefone: '(62) 3506-7112',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Educação infantil em período integral e parcial.',
  },
  {
    id: 'cmei-menino-jesus',
    nome: 'CMEI Menino Jesus',
    tipo: 'CMEI',
    tipoLabel: 'CMEI - Creche Municipal',
    emoji: '👶',
    cor: '#9333ea',
    bgBadge: 'bg-purple-100 text-purple-800 border-purple-300',
    latitude: -16.638400,
    longitude: -49.394500,
    endereco: 'Rua Belo Horizonte, quadra 32',
    bairro: 'Setor Maysa II',
    telefone: '(62) 3506-7115',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Atendimento integral à primeira infância na Região Leste.',
  },
  {
    id: 'cmei-santo-afonso',
    nome: 'CMEI Santo Afonso',
    tipo: 'CMEI',
    tipoLabel: 'CMEI - Creche Municipal',
    emoji: '👶',
    cor: '#9333ea',
    bgBadge: 'bg-purple-100 text-purple-800 border-purple-300',
    latitude: -16.664200,
    longitude: -49.483100,
    endereco: 'Av. Santo Afonso, nº 310',
    bairro: 'Setor Santuário',
    telefone: '(62) 3506-7118',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Educação e desenvolvimento infantil municipal.',
  },

  // --- ESCOLAS MUNICIPAIS ---
  {
    id: 'esc-padre-renato',
    nome: 'Escola Municipal Padre Renato',
    tipo: 'ESCOLA',
    tipoLabel: 'Escola Municipal',
    emoji: '🏫',
    cor: '#2563eb',
    bgBadge: 'bg-blue-100 text-blue-800 border-blue-300',
    latitude: -16.656500,
    longitude: -49.484900,
    endereco: 'Rua do Cruzeiro, nº 450',
    bairro: 'Vila Pai Eterno',
    telefone: '(62) 3506-7130',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Ensino Fundamental I e II com programas de robótica e reforço escolar.',
  },
  {
    id: 'esc-cirandinha',
    nome: 'Escola Municipal Cirandinha',
    tipo: 'ESCOLA',
    tipoLabel: 'Escola Municipal',
    emoji: '🏫',
    cor: '#2563eb',
    bgBadge: 'bg-blue-100 text-blue-800 border-blue-300',
    latitude: -16.652900,
    longitude: -49.492100,
    endereco: 'Rua Couto Magalhães, nº 220',
    bairro: 'Centro',
    telefone: '(62) 3506-7132',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Tradicional unidade municipal de alfabetização e anos iniciais.',
  },
  {
    id: 'esc-alice-ferreira',
    nome: 'Escola Municipal Professora Alice Ferreira do Carmo',
    tipo: 'ESCOLA',
    tipoLabel: 'Escola Municipal',
    emoji: '🏫',
    cor: '#2563eb',
    bgBadge: 'bg-blue-100 text-blue-800 border-blue-300',
    latitude: -16.649100,
    longitude: -49.483800,
    endereco: 'Rua 7, quadra 14',
    bairro: 'Vila Redenção',
    telefone: '(62) 3506-7135',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Ensino Fundamental com biblioteca comunitária e quadra poliesportiva.',
  },
  {
    id: 'esc-wilmar-almeida',
    nome: 'Escola Municipal Dr. Wilmar de Almeida',
    tipo: 'ESCOLA',
    tipoLabel: 'Escola Municipal',
    emoji: '🏫',
    cor: '#2563eb',
    bgBadge: 'bg-blue-100 text-blue-800 border-blue-300',
    latitude: -16.642500,
    longitude: -49.475200,
    endereco: 'Av. Salvador, quadra 11',
    bairro: 'Jardim Salvador',
    telefone: '(62) 3506-7138',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Educação integral e projetos de leitura.',
  },
  {
    id: 'col-padre-anchieta',
    nome: 'Colégio Municipal Padre José de Anchieta',
    tipo: 'ESCOLA',
    tipoLabel: 'Colégio Municipal',
    emoji: '🏫',
    cor: '#2563eb',
    bgBadge: 'bg-blue-100 text-blue-800 border-blue-300',
    latitude: -16.743637,
    longitude: -49.603300,
    endereco: 'Rua Abel Domingues, s/n',
    bairro: 'Distrito de Santa Maria de Trindade',
    telefone: '(62) 3506-7140',
    horario: 'Seg a Sex: 07:00 às 17:30',
    descricao: 'Atendimento educacional no distrito histórico de Santa Maria.',
  },

  // --- PARQUES, PRAÇAS E LAZER PÚBLICO ---
  {
    id: 'parque-lara-guimaraes',
    nome: 'Parque Municipal Lara Guimarães',
    tipo: 'PARQUE',
    tipoLabel: 'Parque Ecológico & Lazer',
    emoji: '🌳',
    cor: '#16a34a',
    bgBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    latitude: -16.663836,
    longitude: -49.492197,
    endereco: 'Rua Cornélia Maria de Souza',
    bairro: 'Vila Pai Eterno',
    horario: 'Aberto diariamente: 06:00 às 22:00',
    descricao: 'Principal parque urbano de Trindade com lago dos pedalinhos, pista de caminhada, academia ao ar livre e quiosques.',
  },
  {
    id: 'parque-ecologico',
    nome: 'Parque Ecológico Municipal de Trindade',
    tipo: 'PARQUE',
    tipoLabel: 'Área Verde e Preservação',
    emoji: '🌿',
    cor: '#16a34a',
    bgBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    latitude: -16.667281,
    longitude: -49.491136,
    endereco: 'Continuação da Av. Manoel Monteiro Sul',
    bairro: 'Setor Sul',
    horario: 'Aberto todos os dias: 06:00 às 20:00',
    descricao: 'Bosque preservado com trilhas arborizadas e nascentes municipais.',
  },
  {
    id: 'praca-prefeitura',
    nome: 'Praça da Prefeitura Municipal',
    tipo: 'PARQUE',
    tipoLabel: 'Praça Pública',
    emoji: '⛲',
    cor: '#15803d',
    bgBadge: 'bg-green-100 text-green-800 border-green-300',
    latitude: -16.655606,
    longitude: -49.489075,
    endereco: 'Em frente ao Palácio das Rosas',
    bairro: 'Vila Pai Eterno',
    horario: 'Livre acesso 24 horas',
    descricao: 'Espaço cívico municipal arborizado, com bancos, iluminação LED e eventos públicos.',
  },
  {
    id: 'praca-basilica',
    nome: 'Praça do Santuário Basílica do Divino Pai Eterno',
    tipo: 'PARQUE',
    tipoLabel: 'Marco Cultural e Turístico',
    emoji: '🕊️',
    cor: '#b45309',
    bgBadge: 'bg-amber-100 text-amber-800 border-amber-300',
    latitude: -16.660752,
    longitude: -49.485396,
    endereco: 'Avenida Doutor Irani Ferreira, s/n',
    bairro: 'Santuário',
    horario: 'Livre acesso 24 horas',
    descricao: 'Grande esplanada de acolhimento de romeiros, eventos culturais e peregrinação.',
  },
  {
    id: 'ginasio-armando-greco',
    nome: 'Ginásio Municipal de Esportes Armando Greco',
    tipo: 'PARQUE',
    tipoLabel: 'Complexo Esportivo Municipal',
    emoji: '⚽',
    cor: '#059669',
    bgBadge: 'bg-teal-100 text-teal-800 border-teal-300',
    latitude: -16.656800,
    longitude: -49.494200,
    endereco: 'Rua Dr. Pedro Ludovico, nº 350',
    bairro: 'Centro',
    telefone: '(62) 3506-7150',
    horario: 'Seg a Sáb: 07:00 às 22:00',
    descricao: 'Quadras poliesportivas para futebol de salão, vôlei, basquete e eventos da comunidade.',
  },
  {
    id: 'praca-lazer-oeste',
    nome: 'Praça Municipal do Lazer',
    tipo: 'PARQUE',
    tipoLabel: 'Praça e Lazer',
    emoji: '🛝',
    cor: '#16a34a',
    bgBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    latitude: -16.659895,
    longitude: -49.496577,
    endereco: 'Av. Raimundo de Aquino com Rua 14',
    bairro: 'Setor Oeste',
    horario: 'Livre acesso',
    descricao: 'Playground infantil, quadra de areia e convivência comunitária.',
  },
];

export const CATEGORIAS_ORGAOS = [
  { id: 'TODOS', label: 'Todos os Órgãos', icon: '🏛️' },
  { id: 'PREFEITURA_SEC', label: 'Prefeitura & Secretarias', icon: '🏛️' },
  { id: 'SAUDE', label: 'UBS & Hospitais / UPA', icon: '🏥' },
  { id: 'EDUCACAO', label: 'Escolas & CMEIs', icon: '🏫' },
  { id: 'PARQUES', label: 'Parques & Praças', icon: '🌳' },
] as const;
